<Project>
	<!-- This line is for ef-core migrations to work without coming into conflict with the BaseIntermediateOutputPath, please DON'T touch EVER -->
	<Import Condition="Exists('$(MSBuildProjectDirectory)\obj\$(MSBuildProjectFile).EntityFrameworkCore.targets')" Project="$(MSBuildProjectDirectory)\obj\$(MSBuildProjectFile).EntityFrameworkCore.targets" />
  
	<PropertyGroup>
		<BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
	</PropertyGroup>
</Project>
