// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Bison.Razor.domain_model;

#nullable disable

namespace Bison.Razor.Migrations
{
    [DbContext(typeof(BisonContext))]
    [Migration("20261001125608_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Post");

                    b.HasDiscriminator().HasValue("Post");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Taxons");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasBaseType("Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ObservationId");

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("Observation", b =>
                {
                    b.HasBaseType("Post");

                    b.Property<int>("TaxonId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("TaxonId");

                    b.HasDiscriminator().HasValue("Observation");
                });

            modelBuilder.Entity("Proposal", b =>
                {
                    b.HasBaseType("Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxonId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ObservationId");

                    b.HasIndex("TaxonId");

                    b.ToTable("Post", t =>
                        {
                            t.Property("ObservationId")
                                .HasColumnName("Proposal_ObservationId");

                            t.Property("TaxonId")
                                .HasColumnName("Proposal_TaxonId");
                        });

                    b.HasDiscriminator().HasValue("Proposal");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("Observation", "Observation")
                        .WithMany("Comments")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("Observation", b =>
                {
                    b.HasOne("Taxon", "Taxon")
                        .WithMany("Observations")
                        .HasForeignKey("TaxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Proposal", b =>
                {
                    b.HasOne("Observation", "Observation")
                        .WithMany("Proposals")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taxon", "Taxon")
                        .WithMany("Proposals")
                        .HasForeignKey("TaxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Observation", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
