name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Windows 
      run: dotnet publish -c Release -r win-x64 --self-contained true -o publish/win
    - name: Publish Linux
      run: dotnet publish -c Release -r linux-x64 --self-contained true -o publish/linux
    - name: Publish macOS
      run: dotnet publish -c Release -r osx-x64 --self-contained true -o publish/mac
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
       name: builds
       path: publish/
